//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_opgave
{
    using System;
    using System.Collections.Generic;
    
    public partial class pizzas
    {
        public int id { get; set; }
        public string name { get; set; }
        public string topping { get; set; }
        public double alm { get; set; }
        public double fam { get; set; }
    }
}
